# Generated by Django 2.2.4 on 2019-08-07 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('village_prefix', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('travelling_time_to_village', models.IntegerField(default=0)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('drug_allergy', models.TextField(default='None')),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('face_encodings', models.CharField(max_length=3000)),
                ('picture_blob', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 7, 17, 47, 39, 182180))),
                ('status', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Patient')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vitals_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('systolic', models.IntegerField(default=0)),
                ('diastolic', models.IntegerField(default=0)),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hiv_positive', models.BooleanField(default=False)),
                ('ptb_positive', models.BooleanField(default=False)),
                ('hepc_positive', models.BooleanField(default=False)),
                ('heart_rate', models.IntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visit')),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
        migrations.CreateModel(
            name='Postreferral',
            fields=[
                ('postreferral_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 7, 17, 47, 39, 183176))),
                ('recorder', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visit')),
            ],
            options={
                'db_table': 'postreferrals',
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fg_value', models.BinaryField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('fg_image', models.BinaryField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Patient')),
            ],
            options={
                'db_table': 'fingerprints',
            },
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('consult_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 7, 17, 47, 39, 187307))),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('problems', models.TextField(blank=True, null=True)),
                ('urine_test', models.TextField(blank=True, null=True)),
                ('hemocue_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('blood_glucose', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('referrals', models.TextField(blank=True, null=True)),
                ('chronic_referral', models.BooleanField(blank=True, null=True)),
                ('addendum', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visit')),
            ],
            options={
                'db_table': 'consults',
            },
        ),
    ]
