# Generated by Django 2.2 on 2019-08-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
