# Generated by Django 2.2.4 on 2019-08-08 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.AlterField(
            model_name='consult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 14, 15, 51, 744949)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture_blob',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='postreferral',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 14, 15, 51, 743985)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 14, 15, 51, 739992)),
        ),
    ]
