# Generated by Django 2.2.4 on 2019-08-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitConsults',
            new_name='VisitConsult',
        ),
    ]
