# Generated by Django 2.2.4 on 2019-08-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0002_auto_20190814_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='local_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
