# Generated by Django 2.2.4 on 2019-10-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0002_auto_20190903_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitconsult',
            name='consult',
        ),
        migrations.RemoveField(
            model_name='visitconsult',
            name='consult_type',
        ),
        migrations.RemoveField(
            model_name='visitconsult',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='consult_type',
        ),
        migrations.AddField(
            model_name='consult',
            name='type',
            field=models.CharField(default='Done', max_length=255, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='dental_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='medical_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ConsultType',
        ),
        migrations.DeleteModel(
            name='VisitConsult',
        ),
    ]
