# Generated by Django 2.2.4 on 2019-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0002_medication_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='addendum_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
