# Generated by Django 2.2 on 2019-08-07 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0002_auto_20190807_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Patient')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
    ]
