# Generated by Django 2.2.4 on 2019-08-08 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0002_auto_20190808_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='picture_blob',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='consult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 14, 19, 9, 570541)),
        ),
        migrations.AlterField(
            model_name='postreferral',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 14, 19, 9, 569540)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 14, 19, 9, 567542)),
        ),
    ]
