# Generated by Django 2.2.4 on 2019-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0003_auto_20191002_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitals',
            new_name='MedicalVitals',
        ),
        migrations.AlterField(
            model_name='consult',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='medicalvitals',
            table='medicalVitals',
        ),
    ]
