# Generated by Django 2.2 on 2019-08-07 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0003_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visits')),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
    ]
