# Generated by Django 2.2.4 on 2019-08-08 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0003_auto_20190808_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 18, 6, 10, 888303)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2019, 8, 8)),
        ),
        migrations.AlterField(
            model_name='postreferral',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 18, 6, 10, 887301)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 18, 6, 10, 884303)),
        ),
    ]
