# Generated by Django 2.2.4 on 2019-08-13 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicmodels', '0003_consult_addendum_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='addendum_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_addendum', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consult',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consult',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Visit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Consult'),
        ),
        migrations.AlterField(
            model_name='order',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Medication'),
        ),
        migrations.AlterField(
            model_name='postreferral',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Visit'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Patient'),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Visit'),
        ),
    ]
