# Generated by Django 2.2.4 on 2019-08-08 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0004_auto_20190808_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 10, 7, 30, 51710, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 10, 7, 30, 46459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postreferral',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 10, 7, 30, 50457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 10, 7, 30, 48457, tzinfo=utc)),
        ),
    ]
