# Generated by Django 2.2.4 on 2019-08-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0004_auto_20190813_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'consulttype',
            },
        ),
        migrations.CreateModel(
            name='VisitConsults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Consult')),
                ('consult_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.ConsultType')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visit')),
            ],
            options={
                'db_table': 'visitconsults',
            },
        ),
        migrations.AddField(
            model_name='consult',
            name='consult_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.ConsultType'),
        ),
    ]
