# Generated by Django 2.2 on 2019-08-07 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0004_vitals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitals',
            old_name='visit_id',
            new_name='visit',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='id',
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_allergy',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='patient',
            name='parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='travelling_time_to_village',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 12, 34, 46, 151177)),
        ),
        migrations.AddField(
            model_name='vitals',
            name='diastolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vitals',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vitals',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vitals',
            name='hepc_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vitals',
            name='hiv_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vitals',
            name='ptb_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vitals',
            name='systolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vitals',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vitals',
            name='vitals_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vitals',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visits',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
