# Generated by Django 2.2.4 on 2019-10-07 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0004_auto_20191002_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(blank=True, null=True)),
                ('intraoral', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('referred_for', models.TextField(blank=True, null=True)),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Visit')),
            ],
            options={
                'db_table': 'dentalVitals',
            },
        ),
    ]
