# Generated by Django 2.2 on 2019-08-07 04:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0005_auto_20190807_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 12, 43, 13, 561803)),
        ),
        migrations.CreateModel(
            name='Postreferrals',
            fields=[
                ('postreferral_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 7, 12, 43, 13, 563808))),
                ('recorder', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visits')),
            ],
            options={
                'db_table': 'postreferrals',
            },
        ),
    ]
