# Generated by Django 2.2.4 on 2019-10-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0005_dentalvitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='treatments_done',
            field=models.TextField(blank=True, null=True),
        ),
    ]
