# Generated by Django 2.2.4 on 2019-10-07 13:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0006_consult_treatments_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='dental_consultation',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='medical_consultation',
        ),
        migrations.AddField(
            model_name='visit',
            name='consultations',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
