# Generated by Django 2.2.4 on 2019-08-07 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '__first__'),
        ('clinicmodels', '0007_auto_20190807_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('consult_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 7, 16, 55, 26, 693206))),
                ('notes', models.TextField()),
                ('diagnosis', models.TextField()),
                ('problems', models.TextField()),
                ('urine_test', models.TextField()),
                ('hemocue_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('blood_glucose', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
            options={
                'db_table': 'consults',
            },
        ),
        migrations.CreateModel(
            name='Postreferral',
            fields=[
                ('postreferral_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 7, 16, 55, 26, 693206))),
                ('recorder', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
            ],
            options={
                'db_table': 'postreferrals',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 8, 7, 16, 55, 26, 692206))),
                ('status', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Patient')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
        migrations.RemoveField(
            model_name='visits',
            name='patient_id',
        ),
        migrations.AlterField(
            model_name='vitals',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visit'),
        ),
        migrations.DeleteModel(
            name='Postreferrals',
        ),
        migrations.DeleteModel(
            name='Visits',
        ),
        migrations.AddField(
            model_name='postreferral',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visit'),
        ),
        migrations.AddField(
            model_name='consult',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.Visit'),
        ),
    ]
