# Generated by Django 2.2.4 on 2019-08-07 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0008_auto_20190807_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 16, 57, 4, 620458)),
        ),
        migrations.AlterField(
            model_name='postreferral',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 16, 57, 4, 620458)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 16, 57, 4, 620458)),
        ),
    ]
