# Generated by Django 2.2.4 on 2019-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0008_auto_20191008_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
