# Generated by Django 2.2.4 on 2019-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0009_auto_20191008_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
