# Generated by Django 2.2.4 on 2019-10-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0012_auto_20191010_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='blood_glucose_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
