# Generated by Django 2.2.4 on 2019-10-10 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0014_auto_20191010_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='date',
        ),
        migrations.AddField(
            model_name='consult',
            name='consult_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
