# Generated by Django 2.2.4 on 2019-10-10 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0015_auto_20191010_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='consult_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 13, 21, 47, 313951, tzinfo=utc)),
        ),
    ]
