# Generated by Django 2.2.4 on 2019-10-10 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0017_auto_20191010_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='consult_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
