# Generated by Django 2.2.4 on 2019-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0019_auto_20191010_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
