# Generated by Django 2.2.4 on 2019-10-11 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0023_auto_20191011_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
