# Generated by Django 2.2.4 on 2019-10-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0024_auto_20191011_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='addendum',
        ),
    ]
