# Generated by Django 2.2.4 on 2019-10-11 13:40

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0025_remove_consult_addendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='addendum',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
