# Generated by Django 2.2.4 on 2019-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0026_consult_addendum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='addendum',
        ),
        migrations.AlterField(
            model_name='consult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
