# Generated by Django 2.2.4 on 2019-10-12 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0028_addendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='addendum',
            name='consult',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Consult'),
        ),
    ]
