# Generated by Django 2.2.4 on 2019-10-12 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0029_addendum_consult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postreferral',
            old_name='recorder',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='postreferral',
            name='visit',
        ),
        migrations.AlterField(
            model_name='postreferral',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
