# Generated by Django 2.2.4 on 2019-10-13 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0030_auto_20191012_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Visit'),
        ),
    ]
