# Generated by Django 2.2.4 on 2019-10-20 06:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0032_auto_20191020_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='drug_allergy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
