# Generated by Django 2.2.4 on 2019-11-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0035_auto_20191029_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
