# Generated by Django 2.2.4 on 2019-11-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0036_auto_20191102_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
