# Generated by Django 2.2.4 on 2019-11-19 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0038_auto_20191118_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='consultations',
        ),
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.Medication')),
            ],
            options={
                'db_table': 'stockTransactions',
            },
        ),
    ]
