# Generated by Django 2.2.4 on 2019-11-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0039_auto_20191119_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='reserve_quantity',
        ),
    ]
