# Generated by Django 2.2.4 on 2019-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0040_auto_20191119_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='referred_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
