# Generated by Django 2.2.4 on 2019-11-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0041_consult_referred_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='sub_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
