# Generated by Django 2.2.4 on 2019-11-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0043_order_medicine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doctor',
            field=models.CharField(default='Dr. Penny Lo', max_length=255),
            preserve_default=False,
        ),
    ]
