# Generated by Django 2.2.4 on 2019-11-22 07:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0044_order_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='face_encodings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
