# Generated by Django 2.2.4 on 2019-12-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0045_auto_20191122_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
